Clear cookies with optional url
ergon/http pull request #11
Opened 2021-10-26 07:53 UTC by graefenhain

2021-10-26 08:09 UTC, shanselm-ergon commented on ios/Plugin/Plugin.swift
> +    private func deleteAllCookies() {
won't compile, `call` and `jar` are not defined.

2021-10-26 08:53 UTC, merged

2021-10-26 08:55 UTC, shanselm-ergon commented on ios/Plugin/CapacitorCookieManager.swift
> +            cookies?.forEach { HTTPCookieStorage.shared.deleteCookie($0) }
Here you could also use `jar.cookies?`, or `let cookies = jar.cookies`

2021-10-26 08:55 UTC, 7-plus-t requested changes

2021-10-26 08:55 UTC, 7-plus-t commented on android/src/main/java/com/getcapacitor/plugin/http/Http.java
> +                URL url = new URL(urlString);
Why transform it to an URL which is then not used?

2021-10-26 08:55 UTC, 7-plus-t commented on android/src/main/java/com/getcapacitor/plugin/http/Http.java
> +                call.reject("Could not parse URL. Check that url has valid format");
Typo: `url` -> `URL`

2021-10-26 08:55 UTC, 7-plus-t commented on android/src/main/java/com/getcapacitor/plugin/http/CapacitorCookieManager.java
> +         * The Webkit CookieManager API has not method to delete a single cookie - looks as if
Typo: `has not` -> `has no`

2021-10-26 08:55 UTC, 7-plus-t commented on android/src/main/java/com/getcapacitor/plugin/http/CapacitorCookieManager.java
> +        String cookieString = webkitCookieManager.getCookie(urlString);
unused

2021-10-26 08:55 UTC, 7-plus-t commented on android/src/main/java/com/getcapacitor/plugin/http/CapacitorCookieManager.java
> +    public void removeAllCookiesFor(String urlString) {
Method named with Swift naming convention (`For` only makes sense having parameter labels).

2021-10-26 08:55 UTC, 7-plus-t commented on ios/Plugin/Plugin.swift
> +            call.resolve()
Does not compile. `call` is not available here.

2021-10-26 08:55 UTC, 7-plus-t commented on ios/Plugin/CapacitorCookieManager.swift
> +            jar.cookies(for: url)?.forEach({ (cookie) in jar.deleteCookie(cookie) })
Brackets not needed, could write:
`jar.cookies(for: url)?.forEach { jar.deleteCookie($0) }`

2021-10-26 08:55 UTC, 7-plus-t commented on ios/Plugin/CapacitorCookieManager.swift
> +            let cookies = HTTPCookieStorage.shared.cookies
Why not use `jar.cookies` and inline as you did above?

2021-10-26 08:55 UTC, 7-plus-t commented on ios/Plugin/CapacitorCookieManager.swift
> +            cookies?.forEach { HTTPCookieStorage.shared.deleteCookie($0) }
use `jar` instead of `HTTPCookieStorage.shared`

2021-10-26 08:55 UTC, 7-plus-t commented on ios/Plugin/Plugin.swift
> +                call.reject("Could not parse URL. Check that url has valid format")
Typo: `url` -> `URL`

2021-10-26 08:55 UTC, 7-plus-t commented on ios/Plugin/Plugin.swift
>          let jar = HTTPCookieStorage.shared
Shouldn't this use cookieManager? Otherwise the clear method is never used.

2021-10-26 08:55 UTC, 7-plus-t commented on ios/Plugin/Plugin.swift
>      @objc func clearCookies(_ call: CAPPluginCall) {
The API would be cleaner if this method would be split into two methods:
`clearCookies(...)` and `clearAllCookies()`

2021-10-26 08:55 UTC, 7-plus-t commented on ios/Plugin/Plugin.swift
> +            jar.cookies(for: url)?.forEach { jar.deleteCookie($0) }
Use cookieManager instead

2021-10-26 08:55 UTC, 7-plus-t commented on ios/Plugin/Plugin.swift
> +    private func deleteAllCookies() {
Method not needed, as it is required in cookieManager

2021-10-26 08:55 UTC, 7-plus-t commented on src/web.ts
> +    options?: HttpMultiCookiesOptions,
Seems weird, that both, `options` and `url` is optional. Would be fixed when splitting the method.

2021-10-26 09:00 UTC, shanselm-ergon commented on src/web.ts
> +    options?: HttpMultiCookiesOptions,
No, the options shouldn't be optional anymore, only the URL in the options. But yes, with a split this problem would be obsolet. 
In the definitions.ts it is not obsolet anymore, so this is only a failure in the web implementation. Did this not crash while building?

2021-10-26 09:21 UTC, graefenhain commented on ios/Plugin/Plugin.swift
> +            call.resolve()
already fixed

2021-10-26 09:27 UTC, graefenhain commented on ios/Plugin/Plugin.swift
> +                call.reject("Could not parse URL. Check that url has valid format")
you mean `URL` -> `url`, right? Typo in comment

2021-10-26 09:27 UTC, graefenhain commented on ios/Plugin/CapacitorCookieManager.swift
> +            jar.cookies(for: url)?.forEach({ (cookie) in jar.deleteCookie(cookie) })
already fixed, realised myself

2021-10-26 09:32 UTC, graefenhain commented on android/src/main/java/com/getcapacitor/plugin/http/Http.java
> +                URL url = new URL(urlString);
To catch the MalformedURLException and then reject the call. But probably there's a better way to check if the URL is valid.

2021-10-26 09:40 UTC, graefenhain commented on android/src/main/java/com/getcapacitor/plugin/http/Http.java
> +                URL url = new URL(urlString);
extracted to a separate method

2021-10-26 10:12 UTC, graefenhain commented on src/web.ts
> +    options?: HttpMultiCookiesOptions,
So splitting the method AND leaving url optional? This is weird as well... Or:
`clearCookies(options: HttpMultiCookiesOptions): Promise<void>;` and
`clearAllCookies(): Promise<void>;` without any options? Is this allowed?

2021-10-26 10:41 UTC, shanselm-ergon commented on src/web.ts
> +    options?: HttpMultiCookiesOptions,
yes, the suggestion looks good.

2021-10-27 08:52 UTC, shanselm-ergon commented on src/web.ts
> +    options?: HttpMultiCookiesOptions,
this should not be optional (only in the options object we have the url optional)