-Clear cookies with optional url
ergon/http pull request #12
Opened 2021-10-26 15:09 UTC by graefenhain

fixed bugs and resolved all review findings

2021-10-26 15:12 UTC, graefenhain commented on android/src/main/java/com/getcapacitor/plugin/http/Http.java
> +        Log.i(getLogTag(), "Clear cookies for url '" + urlString + '"');
Does it make sense to leave the log message (for testing)?

2021-10-26 15:12 UTC, graefenhain commented on ios/Plugin/CapacitorCookieManager.swift
> +        os_log("%{public}@", log: OSLog(subsystem: Bundle.main.bundleIdentifier!, category: ""), type: OSLogType.info, "All cookies successfully deleted")
Does it make sense to leave the log message (for testing)?

2021-10-26 15:12 UTC, graefenhain commented on ios/Plugin/Plugin.swift
> +        os_log("%{public}@", log: OSLog(subsystem: Bundle.main.bundleIdentifier!, category: ""), type: OSLogType.info, "Clear all cookies")
log message?

2021-10-27 08:57 UTC, shanselm-ergon commented on ios/Plugin/Plugin.swift
> +        cookieManager!.deleteAllCookies()
Here we should also add a `call.resolve()` at the end.

2021-10-27 09:00 UTC, shanselm-ergon commented on ios/Plugin/CapacitorCookieManager.swift
> +        os_log("%{public}@", log: OSLog(subsystem: Bundle.main.bundleIdentifier!, category: ""), type: OSLogType.info, "All cookies successfully deleted")
there is no other logging as far as I see. I don't mind a log statement (if it is conform with our other log statements and is filtered in production).

2021-10-27 09:02 UTC, shanselm-ergon commented on android/src/main/java/com/getcapacitor/plugin/http/Http.java
> +            call.reject("Could not parse URL. Check that url has valid format");
naming `URL` and `url`, should be consistent.

2021-10-27 09:05 UTC, shanselm-ergon commented on android/src/main/java/com/getcapacitor/plugin/http/Http.java
> +            cookieManager.removeAllCookies(urlString);
It would be nice, if the `cookieManager` also would provide two methods, like `clearAllCookies()` and `clearCookies(url)`. 
In the manager the `clearCookies(url)` method could internally call `clearAllCookies()` because of the missing logic to clear only cookies for the given url. But it would be encapsulated in the manager.

2021-10-27 13:21 UTC, graefenhain commented on android/src/main/java/com/getcapacitor/plugin/http/Http.java
> +            call.reject("Could not parse URL. Check that url has valid format");
This is copied from the original plugin (iOS-Part). The second url is refering to the parameter -> I suggest putting it in quotes to make this clear

2021-10-28 06:23 UTC, shanselm-ergon commented on android/src/main/java/com/getcapacitor/plugin/http/CapacitorCookieManager.java
> +    public void removeAllCookies(String urlString) {
no parameter needed.

2021-10-28 06:24 UTC, shanselm-ergon commented on android/src/main/java/com/getcapacitor/plugin/http/Http.java
> +        cookieManager.removeAllCookies();
this won't compile at the moment, right?

2021-10-28 07:49 UTC, graefenhain commented on android/src/main/java/com/getcapacitor/plugin/http/CapacitorCookieManager.java
> +    public void removeAllCookies(String urlString) {
ups 🤭

2021-10-28 07:50 UTC, graefenhain commented on android/src/main/java/com/getcapacitor/plugin/http/Http.java
> +        cookieManager.removeAllCookies();
It did. I accidentially added the method removeAllCookies twice - once with and once without parameter (line 137 & 157) 🙄

2021-10-28 08:21 UTC, shanselm-ergon approved these changes

2021-10-28 08:23 UTC, 7-plus-t requested changes

2021-10-28 08:23 UTC, 7-plus-t commented on android/src/main/java/com/getcapacitor/plugin/http/CapacitorCookieManager.java
>           * TODO:
This comment belongs to the method on line 145.

2021-10-28 08:23 UTC, 7-plus-t commented on android/src/main/java/com/getcapacitor/plugin/http/Http.java
> +            new URL(urlString);
This is only checks if the string starts with `http://` or `https://`. Not sure if this is more deceptive than helpful. Maybe skip until it is known how the method for removing cookies by given URL is implemented.
See https://jdoodle.com/ia/iKG

2021-10-28 08:23 UTC, 7-plus-t commented on ios/Plugin/CapacitorCookieManager.swift
> +            jar.cookies(for: url)?.forEach({ jar.deleteCookie($0) })
```suggestion
            jar.cookies(for: url)?.forEach { jar.deleteCookie($0) }
```

2021-10-28 08:23 UTC, 7-plus-t commented on ios/Plugin/CapacitorCookieManager.swift
> +            cookies?.forEach { jar.deleteCookie($0) }
```suggestion
            jar.cookies?.forEach { jar.deleteCookie($0) }
```

2021-10-28 08:23 UTC, 7-plus-t commented on ios/Plugin/CapacitorCookieManager.swift
> +    public func deleteAllCookies() {
What's the difference between this and calling clearCookies with `url = nil`? To be in line with the Android implementation, shouldn't it be 2 methods:
- `clearCookies(for url: URL)`
- `clearAllCookies()`

2021-10-28 08:23 UTC, 7-plus-t commented on src/web.ts
> +   * Clears out cookies by setting them to expire immediately
> by setting them to expire immediately
Are they set to expire? I think at least in Swift they are actually removed from storage entirely.

2021-10-28 11:43 UTC, graefenhain commented on android/src/main/java/com/getcapacitor/plugin/http/Http.java
> +            new URL(urlString);
Since I added a call.reject for invalid URLs, I'll leave it and add this comment.

2021-10-28 11:47 UTC, shanselm-ergon requested changes

2021-10-28 11:47 UTC, shanselm-ergon commented on ios/Plugin/CapacitorCookieManager.swift
> +            let cookies = jar.cookies
not needed anymore

2021-10-28 11:49 UTC, graefenhain commented on ios/Plugin/CapacitorCookieManager.swift
> +    public func deleteAllCookies() {
So this is just a naming issue?

2021-10-28 11:54 UTC, graefenhain commented on ios/Plugin/CapacitorCookieManager.swift
> +            let cookies = jar.cookies
I realized. This was an automatic commit (suggestion from Steven)

2021-10-28 13:47 UTC, shanselm-ergon commented on ios/Plugin/CapacitorCookieManager.swift
> +            let cookies = jar.cookies
Still there

2021-10-28 14:02 UTC, shanselm-ergon commented on src/web.ts
>    ): Promise<void> => Cookie.clearCookies();
a, didn't see that, the web implementation does also not respect the given URL? Interesting.

2021-10-28 14:05 UTC, shanselm-ergon commented on ios/Plugin/CapacitorCookieManager.swift
> +        let jar = HTTPCookieStorage.shared
`jar` is already defined on class level, no need to get it here.

2021-10-28 14:14 UTC, shanselm-ergon commented on android/src/main/java/com/getcapacitor/plugin/http/CapacitorCookieManager.java
> +     * Removes all cookies for the given URL. NOT YET IMPLEMENTED - internally invokes
I would raise an exception with this message (not yet implemented) instead of documenting it. But the method is currently not used, hopefully we remember it later on.

2021-10-28 14:38 UTC, graefenhain commented on android/src/main/java/com/getcapacitor/plugin/http/CapacitorCookieManager.java
> +     * Removes all cookies for the given URL. NOT YET IMPLEMENTED - internally invokes
I reject the call in Http.java
But add the exception here as well.

2021-10-28 14:54 UTC, shanselm-ergon approved these changes

2021-10-28 15:21 UTC, merged